- name: Log in to Azure Red Hat OpenShift (ARO) and create projects
  hosts: localhost
  connection: local
  no_log: false
  vars_files:
    - ./vars-myvars.yml

  tasks:

    - name: Log in to Azure Red Hat OpenShift (ARO)
      k8s_auth:
        host: "{{ aro_api_url }}"
        username: "{{ aro_username }}"
        password: "Microsoft"
      register: k8s_auth_results

    - name: Save API key variable
      set_fact:
        aro_api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

    - name: Create an Azure Red Hat Openshift (ARO) project for Source-To-Image Deploy
      k8s:
        name: "{{ aro_username }}-s2i"
        host: "{{ aro_api_url }}"
        username: "{{ aro_username }}"
        api_key: "{{ aro_api_key }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Create an Azure Red Hat Openshift (ARO) project for Microsoft SQL Server
      k8s:
        name: "{{ aro_username }}-mssql-01"
        host: "{{ aro_api_url }}"
        username: "{{ aro_username }}"
        api_key: "{{ aro_api_key }}"
        api_version: v1
        kind: Namespace
        state: present
