- name: Create App Service Plan to modernize TODO Application
  hosts: localhost
  connection: local

  tasks:
    - name: Create an Azure App Service Plan for TODO Application
      azure.azcollection.azure_rm_appserviceplan:
        name: "summit21-appservice-plan"
        is_linux: true
        number_of_workers: 1
        resource_group: "summit2021"
        sku: S1
